# Generated by Django 4.2.4 on 2024-01-18 22:19

import django.db.models.deletion
from django.db import migrations, models

import activities.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardens', '0002_remove_fertilizationinline_garden_delete_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField()),
                ('quantity_as_float', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True, validators=[activities.validators.validate_unit_measurement])),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('F', 'Fertilisation'), ('P', 'Plantation'), ('C', 'Taille')], max_length=1)),
                ('comment', models.TextField()),
                ('fertilization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.fertilization')),
                ('garden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gardens.garden')),
            ],
        ),
    ]
