# Generated by Django 4.2.4 on 2024-01-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilization',
            old_name='due_date',
            new_name='creation',
        ),
        migrations.AddField(
            model_name='fertilization',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
