# Generated by Django 4.2.4 on 2024-01-16 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import gardens.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('F', 'Fertilisation'), ('P', 'Plantation'), ('T', 'Taille')], max_length=1)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('street', models.CharField(default='', max_length=60)),
                ('city', models.CharField(default='', max_length=60)),
                ('state', models.CharField(blank=True, max_length=60, null=True)),
                ('postal_code', models.CharField(default='', max_length=10)),
                ('country', models.CharField(default='', max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizationInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField()),
                ('quantity_as_float', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True, validators=[gardens.validators.validate_unit_measurement])),
            ],
        ),
        migrations.CreateModel(
            name='GardenOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('F', 'Fertilisation'), ('P', 'Plantation'), ('C', 'Taille')], max_length=1)),
                ('gender', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mme.'), ('MSS', 'Mlle.')], max_length=3)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='fertilizer',
            old_name='is_ecologic',
            new_name='organic',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='fertilisation',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='user',
        ),
        migrations.AddField(
            model_name='garden',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='garden',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='GardenFertilization',
        ),
        migrations.AddField(
            model_name='fertilizationinline',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.garden'),
        ),
        migrations.AddField(
            model_name='activity',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='gardens.garden'),
        ),
        migrations.AddField(
            model_name='garden',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to='gardens.address'),
        ),
    ]
