# Generated by Django 4.2.4 on 2023-12-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer',
            old_name='is_ecologic',
            new_name='organic',
        ),
    ]
