# Generated by Django 4.2.4 on 2023-12-16 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_rename_is_ecologic_fertilizer_organic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('fertilizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gardens.fertilizer')),
            ],
        ),
        migrations.RemoveField(
            model_name='garden',
            name='fertilisation',
        ),
        migrations.DeleteModel(
            name='GardenFertilization',
        ),
        migrations.AddField(
            model_name='fertilization',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.garden'),
        ),
    ]
