# Generated by Django 4.2.4 on 2023-08-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_garden_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
