# Generated by Django 4.2.4 on 2023-09-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_garden_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
