# Generated by Django 4.2.4 on 2023-12-16 13:38

from django.db import migrations, models

import gardens.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_fertilization_remove_garden_fertilisation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilization',
            old_name='date',
            new_name='creation_timestamp',
        ),
        migrations.AddField(
            model_name='fertilization',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[gardens.validators.validate_unit_measurement]),
        ),
    ]
