# Generated by Django 4.2.4 on 2023-12-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0004_rename_date_fertilization_creation_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fertilization',
            new_name='FertilizationInline',
        ),
        migrations.RenameField(
            model_name='fertilizationinline',
            old_name='creation_timestamp',
            new_name='due_date',
        ),
    ]
