# Generated by Django 4.2.4 on 2023-12-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_rename_fertilization_fertilizationinline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizationinline',
            name='fertilizer',
        ),
        migrations.RemoveField(
            model_name='fertilizationinline',
            name='quantity',
        ),
        migrations.AddField(
            model_name='fertilizationinline',
            name='quantity_as_float',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
