# Generated by Django 4.2.4 on 2023-10-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0006_alter_garden_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='user',
        ),
    ]
