# Generated by Django 4.2.4 on 2023-12-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0006_remove_fertilizationinline_fertilizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizationinline',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
