# Generated by Django 4.2.4 on 2023-12-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0007_alter_fertilizationinline_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='system',
            field=models.CharField(choices=[('1', 'métric'), ('2', 'impérial')], default='1', max_length=9),
        ),
    ]
