# Generated by Django 4.2.4 on 2023-12-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0008_garden_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='system',
        ),
    ]
