# Generated by Django 4.2.4 on 2024-01-01 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardens', '0009_remove_garden_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='user',
        ),
        migrations.AddField(
            model_name='garden',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to=settings.AUTH_USER_MODEL),
        ),
    ]
