# Generated by Django 4.2.4 on 2024-01-13 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0011_address_garden_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to='gardens.address'),
        ),
    ]
