# Generated by Django 4.2.4 on 2024-01-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0013_remove_address_zipcode_address_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='latitude',
            new_name='lattitude',
        ),
    ]
