# Generated by Django 4.2.4 on 2024-01-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0014_rename_latitude_address_lattitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lattitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
