# Generated by Django 4.2.4 on 2024-01-13 22:46

import enumfields.fields
from django.db import migrations, models

import gardens.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0015_alter_address_lattitude_alter_address_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', enumfields.fields.EnumField(enum=gardens.utils.Gender, max_length=1)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
