# Generated by Django 4.2.4 on 2024-01-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0016_gardenowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
